"""Versioned data contracts shared by Awesome Capture skills."""

from .contract_runtime import (
    CONTRACT_NAMES,
    ContractError,
    canonical_json_bytes,
    canonical_json_sha256,
    contract_digest,
    detect_contract,
    loads_strict,
    read_json_strict,
    read_json_strict_with_sha256,
    validate_contract,
    validate_file_context,
    verify_contract_bundle,
)
from .bundle_runtime import runtime_digest
from .posix_runtime import (
    FileLock,
    PosixRuntimeError,
    atomic_write_noclobber,
    ensure_dir,
    file_sha256,
    fsync_dir,
    read_regular_file,
    reject_final_symlink,
    require_posix,
    strict_read_json,
    validate_relative_path,
)

__all__ = [
    "CONTRACT_NAMES",
    "ContractError",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "contract_digest",
    "detect_contract",
    "loads_strict",
    "read_json_strict",
    "read_json_strict_with_sha256",
    "runtime_digest",
    "validate_contract",
    "validate_file_context",
    "verify_contract_bundle",
    "FileLock",
    "PosixRuntimeError",
    "atomic_write_noclobber",
    "ensure_dir",
    "file_sha256",
    "fsync_dir",
    "read_regular_file",
    "reject_final_symlink",
    "require_posix",
    "strict_read_json",
    "validate_relative_path",
]
